### ISSUE TITLE
Too long transmission latency times for jros2client

### ISSUE THREAD

**Issue by joaquinlf** [lambdaprime/jros2client#8]
Thanks for the library, it is a great idea for Java programmers.
We have experience long transmission latency times with jros2client. Most of the times we get a latency of about 1 second with peaks of 5 seconds when starting communications. Is that Ok???
In order to make sure that it wasn´t our program, we have conducted several test with the PublisherApp and SubscriberApp for different cases and also with the computer disconnected from internet.  Besides the long latency (about 1 second), the patters obtained are peculiar. 
[latency_report_ros2.pdf](https://github.com/lambdaprime/jros2client/files/13228911/latency_report_ros2.pdf)
We have conducted the same tests with jros1client and the results obtained are very reasonable always bellow 70 msec with averages of 5 milliseconds :
[latency_report.pdf](https://github.com/lambdaprime/jros2client/files/13228995/latency_report.pdf)
The programs we have used are at the end of the reports. We would like to know if that is expected or there is something wrong. Thanks.

**Comment by lambdaprime** [comment]
Hi @joaquinlf 

Thanks for trying jrosclient

> Most of the times we get a latency of about 1 second

I would imagine that this is due to Publisher not sending messages immediately but only when Subscriber requests them. And Subscriber does so only when it receives a heartbeat (every 1sec by default).

There are performance issue we are looking now in #5, once it is complete we will update you (by the way #5 may improve metrics for "long String (about 2000 chars)" test case).

> with peaks of 5 seconds when starting communications

Updated [documentation](http://portal2.atwebpages.com/jrosclient/Quick_Start_jros2client.html#Latency%20of%205%20seconds%20when%20starting%20communications)

Thanks for reports

**Comment by joaquinlf** [comment]
Thanks for looking up into the issue.
Regarding the delay when starting communications, it makes sense since there is no "roscore" and it has somehow to "look up" for the service. Thanks for updating the documentation.
Regarding the 1 second delay, now it makes sense that if we start the publisher before the subscriber we get the exception. I think most people will expect a behaviour similar to ROS1. 
Thanks,
Joaquín

**Comment by lambdaprime** [comment]
Hi @joaquinlf ,

As part of #5 we did some performance optimizations for large messages. Could you please try your tests with [snapshot version](https://github.com/lambdaprime/jros2client/releases/tag/snapshot4).

We expect that it will not reduce 1sec latency but may reduce metrics for  "long String (about 2000 chars)" test case.

**Comment by joaquinlf** [comment]
Thanks, We have only tested now the "One message every 250 milliseconds" case obtaining similar results. In the previous report we did not find a specific correlation with the "size" of the message. Still if latency is more than 1 second that will not work for many robotic applications. At least in our case we can assume a big latency the first time to establish the connection but not for every message.
Thanks for looking into this issue.

**Comment by lambdaprime** [comment]
Hi @joaquinlf 

There is an RTPS [pushMode attribute](https://www.omg.org/spec/DDSI-RTPS/2.3/Beta1/PDF) which affects how messages are delivered:

```
Configures the mode in which the
Writer operates. If
pushMode==true, then the Writer
will push changes to the reader. If
pushMode==false, changes will
only be announced via heartbeats
and only be sent as response to
the request of a reader.
```

Currently **jrosclient** implementation does not allow users to change pushMode and it is always disabled. With that we tried to reduce network traffic between the nodes.

In FastDDS they have pushMode [enabled by default](https://github.com/eProsima/Fast-DDS/blob/1a070975177802b62efed52cd62557be7a6c3eb0/include/fastdds/rtps/writer/RTPSWriter.h#L512)

Looking at [ROS2](https://github.com/ros2/rmw_fastrtps.git) I don't see this being changed. Which means that ROS2 by default has pushMode enabled.

We plan to add pushMode support in couple of weeks and possibly will make it enabled by default to more align with ROS2 default behavior.

Regards,

**Comment by joaquinlf** [comment]
That sounds like very good news. I will be glad to try the pushMode= true whenever you have it available.
Thanks for looking into this issue.

Regards,
Joaquín

**Comment by joaquinlf** [comment]
In case somebody is interested on a study on the ROS and ROS2 latency times that also compares both systems, there is a good paper about it:
https://www.researchgate.net/publication/309128426_Exploring_the_performance_of_ROS2
Regards,
Joaquín

**Comment by lambdaprime** [comment]
Hi @joaquinlf ,

Thanks for sharing the paper

The fix is ready and will be included in v4 we plan to release end of the year.
Until then you can use [prerelease version](https://github.com/lambdaprime/jros2client/releases/tag/snapshot4)

Our test details:
- duration 20sec
- rate instantaneous (without any sleeps, just while loop)
- message size 60_000 bytes

With pushMode disabled:
- Received number of messages: 800
- Max observed latency in ms is 3945
- Avg latency in ms is 1974.59625

With pushMode enabled:
- Received number of messages: 1800
- Max observed latency in ms is 952
- Avg latency in ms is 37.83611111111111

With pushMode enabled and max history size 1_000:
- Received number of messages: 17946
- Max observed latency in ms is 564
- Avg latency in ms is 177.28691630446897

In all cases "Max observed latency" is the latency of a message which was not added to the queue because queue is full. Since your tests publish with fixed, non 0 delay we expect you see lower Max latency as queue will never be full.

Regards,

**Comment by joaquinlf** [comment]
Hi @lambdaprime 
       That looks much better!!
       I will find the time to try it next week.  

Thanks a lot,
Joaquín
